version: '3'
services:
  chatter-pg-nodejs:
    container_name: chatter
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: twitter:twitter@postgres:5432
      PORT: 3000

    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitter
      POSTGRES_DB: twitter
