version: '3'
services:
  nginx:
    build: ./nginx
    links:
      - app1:app1
      - app2:app2
    ports:
      - "80:80"

  app1:
    container_name: chatter1
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: twitter:twitter@postgres:5432
      PORT: 3000

    depends_on:
      - postgres
    links:
      - postgres

  app2:
    container_name: chatter2
    build: .
    ports:
      - 3001:3000
    environment:
      POSTGRES_HOST: twitter:twitter@postgres:5432
      PORT: 3000

    depends_on:
      - postgres
      - redis
    links:
      - postgres

  redis:
    image: redis:alpine
  
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitter
      POSTGRES_DB: twitter
